### ISSUE TITLE
Add link to user guide

### ISSUE THREAD

**Issue by jlblcc** [USFWS/alaska-region-metadata-guide#19]
Can someone with owner privileges add the link to the user guide to the repo settings?

https://usfws.github.io/mdeditor-user-guide-alaska-region/

### Example

![image](https://user-images.githubusercontent.com/5833603/68506818-ed2e6c00-0216-11ea-8bfb-fd150036b63e.png)

**Comment by mccrea-cobb** [comment]
added website link.
