### ISSUE TITLE
Change title to ensure a clear distinction from the authoratative mdEditor User guide

### ISSUE THREAD

**Issue by hamaier** [USFWS/alaska-region-metadata-guide#7]
The current title, "Alaska Region mdEditor Interim User Guide" implies that this is an interim user guide **for** the mdEditor. We should make sure that readers do not confuse our document with the official "[mdEditor User Manual](https://adiwg.gitbooks.io/mdeditor/)". The introduction of our manual states:

> _This manual describes the INTERIM requirements and best practices for the creation of high-quality and consistent metadata records for projects and products from the Alaska Region (AK-Region) of the US Fish and Wildlife Service (USFWS)._

At its core, our manual documents best practices and workflows for describing and archiving data that can be generally applied, even if the mdEditor was not being used. In this case, we just happen to be using the mdEditor to provide examples. For the sake of clarity to the end users, I'm wondering if we should call the document something like:

- Alaska Region Metadata Guide
- Guide to creating metadata using the mdEditor
- Alaska Region data archiving best practices
- Data archiving best practices and workflows: examples using the mdEditor
- other thoughts???

**Comment by mccrea-cobb** [comment]
I agree that there is potential for confusion, and a title change could help alleviate that. I do like generalizing it to "Alaska Region Metadata Guide", but as currently written, this guide is almost entirely focused on how to use mdEditor for creating metadata to the AK standard. I suggest that if we were to broaden the title as suggested, we add more to the intro at least that clarifies that we are describing best practices and workflows for describing data in Alaska region and using mdEditor as the tool of choice for this purpose.

**Comment by mccrea-cobb** [comment]
Changed repo title to "alaska-region-metadata.guide." Updated titles of docs to reflect this change.
